name: pbs.img

on:
  schedule:
    - cron:  "0 0 * * 0"
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Build pbs.img
        run: sudo /bin/bash pbs/build.sh

      - name: Upload iso artifact
        uses: actions/upload-artifact@main
        with:
          name: pbs-img
          path: /tmp/output-pbs/pbs-*.img
