name: pve.img

on:
  schedule:
    - cron:  "0 0 * * 0"
  push:
    branches:
    - main
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Build pve.img
        run: sudo /bin/bash pve/build.sh

      - name: Upload iso artifact
        uses: actions/upload-artifact@main
        with:
          name: pve-img
          path: /tmp/output-pve/pve-*.img
