name: vyos.img

on:
  schedule:
    - cron:  "0 0 * * 0"
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Build vyos.img
        run: sudo /bin/bash vyos/build.sh

      - name: Upload iso artifact
        uses: actions/upload-artifact@main
        with:
          name: vyos-img
          path: /tmp/output-vyos-rolling-amd64/vyos-*.img
